<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<link rel="stylesheet" href="../css/bootstrap.min.css">
	<link rel="stylesheet" href="../css/bootstrap-theme.min.css">
	<link rel="stylesheet" href="estilos.css">
	
</head>
<body>
	

<div class="container">
	<h1>Este es un header H1</h1>
	<h2>Este es un header H2</h2>
	<h3>Este es un header H3</h3>
	<h4>Este es un header H4</h4>
	<h5>Este es un header H5</h5>
	<h6>Este es un header H6</h6>

	<div class="row">
		<div class="col-md-4"></div>
		<div class="col-md-4"></div>
		<div class="col-md-4"></div>
	</div>
</div>





<script src="../js/jquery-1.11.3.min.js"></script>
<script src="../js/bootstrap.min.js"></script>
</body>
</html>