<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<link rel="stylesheet" href="../css/bootstrap.min.css">

	<!-- Optional theme
	<link rel="stylesheet" href="../css/bootstrap-theme.min.css">
	-->
	
</head>
<body>

<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h2>Titulo prueba</h2>
			<p>
				archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años, sino que tambien ingresó como texto de relleno en documentos electrónicos, quedando esencialmente igual al original. 
			</p>
			
			<input class="btn btn-info pull-left" type="button" value="Informacion">
			<input class="btn btn-primary pull-right" type="button" value="Primario">
		</div>
	</div>

	<div class="row">

		<div class="col-md-12">
			<h2>Titulo 2</h2>
			<div style="width:300px;" class="bg-success center-block">
				Es un hecho establecido hace demasiado tiempo que un lector se distraerá con el contenido del texto de un sitio mientras que mira su diseño. El punto de usar Lorem Ipsum es que tiene una distribución más o menos normal de las letras, al contrario de usar textos como por ejemplo "Contenido aquí, contenido aquí".
			</div>
		</div>
		
	</div>
</div>


<script src="../js/jquery-1.11.3.min.js"></script>
<script src="../js/bootstrap.min.js"></script>
</body>
</html>