<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<link rel="stylesheet" href="../css/bootstrap.min.css">
	<link rel="stylesheet" href="../css/bootstrap-theme.min.css">
	<link rel="stylesheet" href="estilos.css">
	
</head>
<body>
	

<div class="container">
	<h1 class="text-muted">Este es un header H1  <small>Texto secundario</small></h1>
	<h2 class="text-primary">Este es un header H2  <small>Texto secundario</small></h2>
	<h3 class="text-warning">Este es un header H3  <small>Texto secundario</small></h3>
	<h4 class="text-info">Este es un header H4  <small>Texto secundario</small></h4>
	<h5 class="text-success">Este es un header H5  <small>Texto secundario</small></h5>
	<h6 class="text-danger">Este es un header H6  <small>Texto secundario</small></h6>

	<h1 class="bg-primary">Este es un header H1  <small>Texto secundario</small></h1>
	<h2 class="bg-success">Este es un header H2  <small>Texto secundario</small></h2>
	<h3 class="bg-info">Este es un header H3  <small>Texto secundario</small></h3>
	<h4 class="bg-warning">Este es un header H4  <small>Texto secundario</small></h4>
	<h5 class="bg-danger">Este es un header H5  <small>Texto secundario</small></h5>

	<div class="row">
		<div class="col-md-4">
			<p class="lead">Lorem Ipsum es simplemente el texto de relleno de las imprentas</p>
			<p class=""><mark>Lorem Ipsum es simplemente el texto de relleno de las imprentas </mark></p>
			<p class=""><del>Lorem Ipsum es simplemente el texto de relleno de las imprentas</del></p>
			<p class=""><s>Lorem Ipsum es simplemente el texto de relleno de las imprentas</s></p>
	</div>
		<div class="col-md-4 text-justify">
			<p class=""><ins>Lorem Ipsum es simplemente el texto de relleno de las imprentas</ins></p>
			<p class="text-uppercase"><u>Lorem Ipsum es simplemente el texto de relleno de las imprentas</u></p>
			<p class="small">Lorem Ipsum es simplemente el texto de relleno de las imprentas</p>
			<p class="">Lorem Ipsum es simplemente el texto de relleno de las imprentas</p>
	</div>
		<div class="col-md-4">
			<p class=""><pre>Lorem Ipsum es simplemente el texto de relleno de las imprentas</pre></p>
			<p class=""><code>Lorem Ipsum es simplemente el texto de relleno de las imprentas</code></p>
			<p class="">Lorem Ipsum es simplemente el texto de relleno de las imprentas</p>
			<p class="">Lorem Ipsum es simplemente el texto de relleno de las imprentas</p>
	</div>
	</div>

	<div class="row">
		<blockquote>
			<p>
				laksdl aslkd alskd alks dlaks dlka sldk alskd alks dlk k
			</p>
			<footer>
				Santiago <cite title="Fuente">en Fuente</cite>
			</footer>
		</blockquote>
	</div>
</div>





<script src="../js/jquery-1.11.3.min.js"></script>
<script src="../js/bootstrap.min.js"></script>
</body>
</html>