<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<link rel="stylesheet" href="../css/bootstrap.min.css">
	<link rel="stylesheet" href="../css/bootstrap-theme.min.css">
	<link rel="stylesheet" href="estilos.css">
	
</head>
<body>



<div class="container">
	<form class="form-horizontal" action="">
		<div class="form-group has-error">
			<label class="control-label col-md-2" for="nombre">Nombre</label>
			<div class="col-md-10">
				<input class="form-control" type="nombre" id="nombre" placeholder = "input basico">
			</div>	
		</div>
		
		<div class="form-group">
			<label for="contacto" class="control-label col-md-2">Contacto</label>
			<div class="col-md-4">
				<input type="text" name="" id="contacto" class="form-control" placeholder="Contacto" disabled>
			</div>
			<label for="contacto" class="control-label col-md-1">Contacto</label>
			<div class="col-md-4">
				<input type="text" name="" id="contacto" class="form-control" placeholder="Contacto" disabled>
			</div>
		</div>

			<div class="form-group">
				<label class="control-label col-md-2" for="option">Elige una opcion</label>
				<div class="col-md-10">
					<select class="form-control" name="opciones" id="option">
						<option value="" class="">Opcion1</option>
						<option value="" class="">Opcion 2</option>
						<option value="" class="">Opcion 3</option>
						<option value="" class="">Opcion 4</option>
						<option value="" class="">Opcion 5</option>
					</select>
				</div>
				
			</div>
		

			<div class="form-group has-success">
				<label class="control-label col-md-2" for="mensaje">Mensaje</label>
				<div class="col-md-10">
					<textarea class="form-control" placeholder = "textarea" name="lost" id="mensaje" cols="" rows=""></textarea>
				</div>
			</div>
					
				<div class="form-group">
					<label class="control-label col-md-2" for="archivo">Archivo</label>
					<div class="col-md-10">
						<input type="file" name="archivo" id="archivo">
					</div>
				
				</div>
					
			<div class="form-group">
				<div class="col-md-2 col-md-offset-2">
					<p class="help-block">Maximo 50mb</p>
				</div>
				
			</div>
			<div class="form-group">
				<div class="col-md-2 col-md-offset-2">
						<button class="btn btn-primary">Enviar</button>
				</div>
			</div>

			<div class="checkbox">
				<label for="">
					<input type="checkbox" name="ch1" id="ch1" class="">Ch1
				</label>
			</div>
			<div class="checkbox">
				<label for="">
					<input type="checkbox" name="ch1" id="ch1" class="">Ch2
				</label>
			</div>
			<div class="checkbox">
				<label for="">
					<input type="checkbox" name="ch1" id="ch1" class="">Ch3
				</label>
			</div>


			
				<label class="checkbox-inline" for="ch1">
					<input type="checkbox" name="ch1" id="ch1" class="">Ch1
				</label>
			
				<label class="checkbox-inline" for="ch2">
					<input type="checkbox" name="ch1" id="ch2" class="">Ch2
				</label>
			
			
				<label class="checkbox-inline" for="ch3">
					<input type="checkbox" name="ch1" id="ch3" class="">Ch3
				</label>
			


			<div class="radio">
				<label for="radio1">
					<input type="radio" name="ch1" id="radio1" class="">R1
				</label>
			</div>
			<div class="radio">
				<label for="radio2">
					<input type="radio" name="ch1" id="radio2" class="">R2
				</label>
			</div>
			<div class="radio">
				<label for="radio3">
					<input type="radio" name="ch1" id="radio3" class="">R3
				</label>
			</div>

	</form>
</div>
	

	

<script src="../js/jquery-1.11.3.min.js"></script>
<script src="../js/bootstrap.min.js"></script>
</body>
</html>