<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<link rel="stylesheet" href="../css/bootstrap.min.css">
	<link rel="stylesheet" href="../css/bootstrap-theme.min.css">
	<link rel="stylesheet" href="estilos.css">
	
</head>
<body>



<div class="container">
	<form action="">
		<div class="form-group">
			<label for="nombre">Nombre</label>
			<input class="form-control" type="nombre" id="nombre" placeholder = "input basico">
		</div>
		

	<div class="form-group">
		<label for="option">Elige una opcion</label>
		<select class="form-control" name="opciones" id="option">
			<option value="" class="">Opcion1</option>
			<option value="" class="">Opcion 2</option>
			<option value="" class="">Opcion 3</option>
			<option value="" class="">Opcion 4</option>
			<option value="" class="">Opcion 5</option>
		</select>
	</div>
		

<div class="form-group">
	<label for="mensaje">Mensaje</label>
		<textarea class="form-control" placeholder = "textarea" name="lost" id="mensaje" cols="" rows=""></textarea>
</div>
		
	<div class="form-group">
		<label for="archivo">Archivo</label>
		<input type="file" name="archivo" id="archivo">
	</div>
		
<div class="form-group">
	<p class="help-block">Maximo 50mb</p>
</div>
		
		<button class="btn btn-primary">Enviar</button>
	</form>
</div>
	

	

<script src="../js/jquery-1.11.3.min.js"></script>
<script src="../js/bootstrap.min.js"></script>
</body>
</html>