<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<link rel="stylesheet" href="../css/bootstrap.min.css">
	<link rel="stylesheet" href="../css/bootstrap-theme.min.css">
	<link rel="stylesheet" href="estilos.css">
	
</head>
<body>


<div class="container">
	<form action="" class="form-inline">
		<div class="form-group">
			<div class="input-group">
				<label class="sr-only" for="nombre">Nombre</label>
				<input class="form-control" type="text" id="nombre" placeholder="Nombre">	
			</div>
		</div>
		<div class="form-group">
			<div class="input-group">
				<label class="sr-only" for="email">email</label>
				<input class="form-control" type="email" name="correo" id="email" placeholder="Email">
			</div>
			<div class="input-group">
				<label class="sr-only" for="email">email</label>
				<input class="form-control" type="email" name="correo" id="email" placeholder="Email">
			</div>
		</div>

		<div class="checkbox">
			<input type="checkbox" name="recuerda" id="recuerda"><label for="recuerda">Recuerdame</label>
		</div>

		<button class="btn btn-primary">Enviar</button>
	</form>
		
</div>




<script src="../js/jquery-1.11.3.min.js"></script>
<script src="../js/bootstrap.min.js"></script>
</body>
</html>