<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<link rel="stylesheet" href="../css/bootstrap.min.css">

	<!-- Optional theme
	<link rel="stylesheet" href="../css/bootstrap-theme.min.css">
	-->
	
</head>
<body>


<div class="container-fluid">
	<div class="row">
		<div class="col-md-2">
			<img src="http://lorempixel.com//700/700/" class="img-responsive img-rounded"  alt="Homero">
		</div>
		<div class="col-md-2">
			<img src="http://lorempixel.com//700/700/" class="img-responsive img-circle" alt="Homero">
		</div>
		<div class="col-md-2">
			<img src="http://lorempixel.com//700/700/" class="img-responsive img-" alt="Homero">
		</div>
	</div>
</div>


<script src="../js/jquery-1.11.3.min.js"></script>
<script src="../js/bootstrap.min.js"></script>
</body>
</html>