<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<link rel="stylesheet" href="../css/bootstrap.min.css">

	<!-- Optional theme
	<link rel="stylesheet" href="../css/bootstrap-theme.min.css">
	-->
	
</head>
<body>


<div class="container">
	<div class="row">
		<div class="col-md-3">
			<button class="btn btn-default">Default</button>
			<button class="btn btn-primary">primary</button>
			<button class="btn btn-success">Success</button>
			<button class="btn btn-info">Info</button>
			<button class="btn btn-warning">Warning</button>
			<button class="btn btn-danger">Danger</button>
			<button class="btn btn-link">Link</button>
		</div>
		<div class="col-md-3">
			<a href="" class="">Default</a>
			<a href="" class="">primary</a>
			<a href="" class="">Success</a>
			<a href="" class="">Info</a>
			<a href="" class="">Warning</a>
			<a href="" class="">Danger</a>
			<a href="" class="">Link</a>
		</div>
	</div>
</div>




<script src="../js/jquery-1.11.3.min.js"></script>
<script src="../js/bootstrap.min.js"></script>
</body>
</html>